### PR TITLE
Fix Selenium tests to run against all environments 

### PR DESCRIPTION
**Pull request by ramezsaeed**
### Description

Selenium test automation for Dashboard

### Changes

- Fix homepage tests (8 tests)
- fix the config and generated url to be able to run the tests on different env (dev, qa, test and main)
- update the documentation

### Tested Scenarios

testrun on github actions
[A list of scenarios tried to match the deliverables](https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/11935574800)

#### Preliminary Checks:

- Does it completely address the issue linked?
- What about edge cases?
- Does it meet the specified acceptance criteria?
- Are there any unintended side effects?
- Does the PR adhere to the team's coding conventions, style guides, and best practices?
- Does it integrate well with existing features?
- Does it impact the overall performance of the application?
- Are there any bottlenecks or slowdowns?
- Has it been optimized for efficiency?
- Has it been adequately tested with unit, integration, and end-to-end tests?
- Are there any known defects or issues?
- Is the code well-documented?
- Are changes to documentation reflected in the code?

#### UI Checks:

- If a UI design is provided/ does it follow it?
- Does every button work?
- Is the data displayed logical? Is it what you expected?
- Does every validation work?
- Does this interface feel intuitive?
- What about slow network? Offline?
- What if the gridproxy/graphql/chain is failing?
- What would a first time user have a hard time navigating here?

#### Code Quality Checks:

- Code formatted/linted? Are there unused imports? .. etc
- Is there redundant/repeated code?
- Are there conditionals that are always true or always false?
- Can we write this more concisely?
- Can we reuse this code? If yes, where?
- Will the changes be easy to maintain and update in the future?
- Can this code become too complex to understand for other devs?
- Can this code cause future integration problems?

### Checklist

- [x] Tests included
- [x] Build pass
- [x] Documentation
- [x] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Review by 0oM4R — COMMENTED** [review]
please fix codacy workflow  errors

**Review by khaledyoussef24 — APPROVED** [review]

**Comment by khaledyoussef24** [comment]
The contact check is still failing

**Comment by khaledyoussef24** [comment]
Codacy check still failing

**Review by khaledyoussef24 — APPROVED** [review]

**Comment by samaradel** [comment]
work flow run fails

**Review by amiraabouhadid — APPROVED** [review]

**Pull request merged**
