### PR TITLE
Add search capabilities in dedicated nodes page

### PR DESCRIPTION
**Pull request by Mahmoud-Emad**
### Description

Created a new layout component for the new dedicated nodes view, added action/mutation type, and added a watcher on the search input value change to request the grid proxy with the new value.

### Changes

- Created mutation and used It instead of hard-coded
- add `dedicatedNodes`, `dedicatedNodesFilter`, `dedicatedNodesTablePageSize`, `dedicatedNodesTablePageNumber` and `dedicatedNodesCount` fields inside the PortalState point to the dedicated nodes view.
- Created a layout for the dedicated nodes page
- Support filter nodes inside the dedicated nodes view

### Supported keys
- CPU <GB>
- memory <GB>
- SSD disk <GB>
- HDD disk <GB>
- GPU's vendor name
- GPU's vendor id
- GPU's device name
- GPU's device id

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/721

### Screens
- image

- image

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Review by zaelgohary — CHANGES_REQUESTED** [review]
I noticed the nodes table is not shown completely although there's enough space around it. I think it would be better to remove/reduce the space in order for the table to be shown completely.

image

**Review by zaelgohary — CHANGES_REQUESTED** [review]
Vendor ID & Device ID are not shown in the table so I think it's safe to remove them from the filters.

image

**Review by zaelgohary — COMMENTED** [review]
When I filter by exisiting MRU value, some elligible nodes disappears.

image

image

**Comment by Mahmoud-Emad** [comment]
> 

The proxy returned the data as seen [here](https://gridproxy.dev.grid.tf/nodes?status=up&ret_count=true&page=1&size=10&rented=true&free_sru=&free_mru=33285996544). However, please note that the values displayed in the node table represent the total, not the free capacity [see here](https://gridproxy.dev.grid.tf/nodes?status=up&ret_count=true&page=1&size=10&rented=true&free_sru=&total_mru=33285996544).

**Comment by Mahmoud-Emad** [comment]
> When I filter by exisiting MRU value, some elligible nodes disappears.
> 
> image
> 
> image
The proxy returned the data as seen [here](https://gridproxy.dev.grid.tf/nodes?status=up&ret_count=true&page=1&size=10&rented=true&free_sru=&free_mru=33285996544). However, please note that the values displayed in the node table represent the total, not the free capacity [see here](https://gridproxy.dev.grid.tf/nodes?status=up&ret_count=true&page=1&size=10&rented=true&free_sru=&total_mru=33285996544).

**Comment by Mahmoud-Emad** [comment]
> I noticed the nodes table is not shown completely although there's enough space around it. I think it would be better to remove/reduce the space in order for the table to be shown completely.
> 
> image

image

image

Please take a look again.

**Comment by AhmedHanafy725** [comment]
I don't think we need to have `free` filters here, the user is going to rent the whole node so he needs to filter them by the total resources of the node.

**Review by AhmedHanafy725 — APPROVED** [review]

**Review by zaelgohary — APPROVED** [review]

**Pull request merged**
