### PR TITLE
Add compute capacity unit tests

### PR DESCRIPTION
**Pull request by zaelgohary**
### Description

Add compute capacity unit tests

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2448

### Checklist

- [x] Tests included
- [x] Build pass
- [ ] Documentation
- [x] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Review by xmonader — COMMENTED** [review]
Really good progress

I shouldn't be able to construct a class in invalid state, so what I suggest is we maybe introduce a constructor that enforces our invariants. 

That being said, I should be expecting the following
1- valid state scenarios to construct e.g a for loop to create computecapacity with numbers (or use a library to generate these)
2- checks for invariants e.g in negative, zeros, decimals, non-ints, boundary values, overflow values, and special numbers like min/max for ram and cpu and ensuring you can't initialize less or higher than them

**Review by Mahmoud-Emad — APPROVED** [review]
The code looks good to me. However, when I tried to run all of the tests, including yours, nothing happened, and my laptop crashed. Please have someone else run the tests instead of me.

**Comment by zaelgohary** [comment]
> The code looks good to me. However, when I tried to run all of the tests, including yours, nothing happened, and my laptop crashed. Please have someone else run the tests instead of me.

Does this happen every time you run these tests?

**Review by amiraabouhadid — CHANGES_REQUESTED** [review]
fails 
image
image

**Comment by zaelgohary** [comment]
> fails image image

Because the validation doesn't work in all workloads. The tests are implemented correctly though.

**Review by amiraabouhadid — APPROVED** [review]

**Pull request merged**
