### PR TITLE
farms dialog

### PR DESCRIPTION
**Pull request by amiraabouhadid**
### Description

move farm dialog to farms to ensure consistent closing, delete unnecessary farms dialog component

### Changes

- moved farms dialog into farms.vue 
- deleted farms dialog component

### Related Issues

#1307 

https://www.loom.com/share/38e5beea9efb4f0c82dc978fd9668253?sid=9a6c1f8f-f87c-4caf-b03c-f8d134df66ee

### CODE REVIEW

**Review by mohamedamer453 — COMMENTED** [review]
- Imo the close button should be moved to the top right corner to be consistent with other dialogs in the dashboard.

   image

**Review by zaelgohary — COMMENTED** [review]
All good except for the close button.

**Comment by amiraabouhadid** [comment]
@zaelgohary close button was made to be consistent with nodes dialog below 
image

**Comment by zaelgohary** [comment]
Now the two headers background is a bit too much. Maybe we can reduce the toolbar's header height and change its color to match the background of the toolbar itself?

image

**Review by mohamedamer453 — APPROVED** [review]

**Review by zaelgohary — APPROVED** [review]

**Pull request merged**
