### PR TITLE
fix sentry console toast error by updating theme handling

### PR DESCRIPTION
**Pull request by amiraabouhadid**
### Changes

- updating current theme retrieval in custom toast 

### Related Issues

#3415

### Tested Scenarios

- tested in light , dark, and system mode

### CODE REVIEW

**Review by 0oM4R — COMMENTED** [review]
the error is not appear, but i have an issue with changing the mode 

[Screencast from 2024-10-08 14-36-57.webm](https://github.com/user-attachments/assets/30a5e99c-8d05-4467-878e-7dcdf05fd105)

**Comment by amiraabouhadid** [comment]
@0oM4R The code changes in this PR do not alter the APP_CURRENT_THEME in localStorage. this issue is tracked here #3494

**Comment by 0oM4R** [comment]
> @0oM4R The code changes in this PR do not alter the APP_CURRENT_THEME in localStorage. this issue is tracked here #3494

so we are validating only the sentry error ?

**Comment by amiraabouhadid** [comment]
@0oM4R yes

**Review by 0oM4R — APPROVED** [review]

**Review by samaradel — APPROVED** [review]

**Pull request merged**
