### PR TITLE
add loading page

### PR DESCRIPTION
**Pull request by mohamedamer453**
### Description

Added a loading screen for the playground.

### Changes

A loading screen was added and it shows a loading animation until the page is ready.

[TF Playground _ Twin.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/60e05cf7-1fe2-4a1c-9d59-cb21fd9661a4)

and in case of slow/throttled connection it will show a message after 30 seconds mentioning that the connection seems to be slow.

[Screencast from 31-10-23 14:13:03.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/06b2343c-b617-4837-abcb-0c81e23543ad)

### Related Issues

#592 

### Checklist

- [ ] Tests included
- [x] Build pass
- [ ] Documentation
- [x] Code format and docstrings
- [x] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Comment by xmonader** [comment]
This looks very cool!

**Review by maayarosama — APPROVED** [review]

**Comment by AhmedHanafy725** [comment]
great job! 

I feel the font of `Your connection seems to be slow, Please wait...` is small

@ehab-hassan can you check it?

**Comment by ehab-hassan** [comment]
@mohamedamer453 
can change font-size to 18 px or larger and font-family "Roboto"

**Comment by mohamedamer453** [comment]
> @mohamedamer453 can change font-size to 18 px or larger and font-family "Roboto"

Sure thing will update it.

**Review by amiraabouhadid — APPROVED** [review]
looks good!

**Review by AhmedHanafy725 — APPROVED** [review]

**Pull request merged**
