### PR TITLE
fix sorting

### PR DESCRIPTION
**Pull request by mohamedamer453**
### Description

- Fixed the sorting for the vm deployment list and k8s deployment list.
- Disabled the sorting for the networks and actions columns.

### Changes

Sorting is working now and sorting for networks/actions columns was disabled.

- VM

   [Screencast from 02-11-23 14:28:43.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/6cc44dec-d3d8-4b21-8237-e5ed598d7af3)

- K8s

   [Screencast from 02-11-23 14:29:43.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/1f31ad62-4074-4a73-aae3-c1366dbcdb76)

### Related Issues

#324 

### Checklist

- [ ] Tests included
- [x] Build pass
- [ ] Documentation
- [x] Code format and docstrings
- [x] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Comment by amiraabouhadid** [comment]
Maybe we can make the sorting arrow beside "Name" visible before clicking? I wouldn't have known it was there if you did not record a screencast of using it. It isn't visible before clicking in both light and dark mode.

**Comment by amiraabouhadid** [comment]
Please also show the horizontal scrollbar in the table on smaller screens.

**Comment by mohamedamer453** [comment]
> Maybe we can make the sorting arrow beside "Name" visible before clicking? I wouldn't have known it was there if you did not record a screencast of using it. It isn't visible before clicking in both light and dark mode.

added in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1348/commits/ddc68bce03c75df18e292ddc89296d65ab9a9380

image



> Please also show the horizontal scrollbar in the table on smaller screens.

a horizontal scrollbar is already available at the bottom of the table on smaller window sizes.

image

**Review by amiraabouhadid — APPROVED** [review]
looks good, thanks

**Comment by zaelgohary** [comment]
@mohamedamer453 can you pull the latest from base branch?

**Review by maayarosama — APPROVED** [review]

**Pull request merged**
