### PR TITLE
Add email input

### PR DESCRIPTION
**Pull request by samaradel**
### Description

Add email input to
- connect your wallet tab
- your profile page 
- TfChain wallet dialog

### Changes

[Screencast from 22-02-24 13:22:39.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/ae1143b3-6f47-4899-8468-2c61bfd4aa6c)

### Related Issues

- [#2066](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2066)
### Checklist

- [ ] Tests included
- [x] Build pass
- [x] Documentation
- [x] Code format and docstrings
- [x] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Comment by samaradel** [comment]
> @samaradel Good job. Just one comment. Some solutions use email input in its form. Maybe we should set the default email value to the user email? What do you think?

Awesome,  totally agree

**Review by amiraabouhadid — CHANGES_REQUESTED** [review]
Please make email field responsive in profile page 
image

**Comment by samaradel** [comment]
@amiraabouhadid fixed

image

**Comment by AlaaElattar** [comment]
- Why it requests to refresh, when i wanted to add my email ?
[Screencast from 02-21-2024 01:07:35 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/dc21a2e0-0975-4513-ac46-79b55012a3f2)

**Comment by AlaaElattar** [comment]
also updating the email takes long time

**Comment by AlaaElattar** [comment]
- The connect button took long time to start reloading.
- Also updating the email took long time.

[Screencast from 02-21-2024 01:11:25 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/f764fabb-8f4e-43ee-85db-7b02d0ce20a1)

**Comment by AlaaElattar** [comment]
- Why this is happened when i wanted to login again !!

[Screencast from 02-21-2024 01:18:46 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/d1ddd97d-5812-4ebd-9b6d-2602ffc2ef1c)

**Comment by samaradel** [comment]
@AlaaElattar fixed

**Comment by MohamedElmdary** [comment]
@samaradel Can we disable `save` btn while saving user's email as reclicking it will duplicate logic

**Comment by samaradel** [comment]
> @samaradel Can we disable `save` btn while saving user's email as reclicking it will duplicate logic

fixed

**Comment by AlaaElattar** [comment]
> @samaradel Good job. Just one comment. Some solutions use email input in its form. Maybe we should set the default email value to the user email? What do you think?

This comment is not applied yet

**Comment by samaradel** [comment]
> > @samaradel Good job. Just one comment. Some solutions use email input in its form. Maybe we should set the default email value to the user email? What do you think?
> 
> This comment is not applied yet

created an issue for this [#2188](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2188)

**Review by AlaaElattar — APPROVED** [review]

**Review by amiraabouhadid — APPROVED** [review]

**Pull request merged**
