### PR TITLE
Enhace unlock contracts dialog

### PR DESCRIPTION
**Pull request by 0oM4R**
### Description

enhance style of unlock contracts dialog,  

### Changes

- include the cost of unlock contracts 
Screenshot from 2024-07-07 12-14-03

Screenshot from 2024-07-07 12-13-49
 
- fix the header style of lock details
Screenshot from 2024-07-07 12-13-56

- fix calculating the available balance 
 
### Related Issues

- #3081

### Documentation PR

For UI changes, Please provide the Documetation PR on [info_grid](https://github.com/threefoldtech/info_grid)

### Checklist

- [ ] Tests included
- [x] Build pass
- [ ] Documentation
- [x] Code format and docstrings
- [x] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Review by amiraabouhadid — APPROVED** [review]

**Comment by samaradel** [comment]
image
image

please make sure that the action buttons are consistent with the rest of dialoges

**Comment by 0oM4R** [comment]
> image image
> 
> please make sure that the action buttons are consistent with the rest of dialoges

@samaradel please clarify what do you mean by make it consistent, this first screenshot have a disabled action button

**Comment by samaradel** [comment]
@0oM4R I mean, the space between the action btn and the dialog is different in the 2 dialogs I mentioned

**Comment by 0oM4R** [comment]
will include the enhancements in development pr

**Pull request merged**
