### PR TITLE
add spacing to scan qr code text in profile card

### PR DESCRIPTION
**Pull request by amiraabouhadid**
### Changes

- removed cols strict specs

### Related Issues

#3642

### Tested Scenarios

- tried on multiple screen size, different zoom %

### Checklist

- [x] Screenshots/Video attached (needed for UI changes)
https://www.loom.com/share/4084e3e1e2724315a6fbe548c3a63dda?sid=5f4adf06-be6b-47b5-bd6a-b9cb1199b892

### CODE REVIEW

**Comment by maayarosama** [comment]
Can you fix in twin details too?
Screenshot from 2024-11-19 12-20-32

**Comment by amiraabouhadid** [comment]
> Can you fix in twin details too? Screenshot from 2024-11-19 12-20-32

the changes are in the twin details so not sure what you mean by this haha, please view above screencast. added a margin anyway

**Review by ehab-hassan — APPROVED** [review]

**Comment by maayarosama** [comment]
> > Can you fix in twin details too? Screenshot from 2024-11-19 12-20-32
> 
> the changes are in the twin details so not sure what you mean by this haha, please view above screencast. added a margin anyway

The word account in twin details has no margin added to the right as shown in the picture

**Review by 0oM4R — APPROVED** [review]

**Comment by amiraabouhadid** [comment]
> > > Can you fix in twin details too? Screenshot from 2024-11-19 12-20-32
> > 
> > 
> > the changes are in the twin details so not sure what you mean by this haha, please view above screencast. added a margin anyway
> 
> The word account in twin details has no margin added to the right as shown in the picture

are you sure you're on this branch? there is a margin as shown in the screencast above

**Review by maayarosama — APPROVED** [review]

**Pull request merged**
