### PR TITLE
Add the rest of solution scripts to deploy an instance from the Grid Client.

### PR DESCRIPTION
**Pull request by A-Harby**
### Description

Add the scripts for the applications (Algorand, Discourse, NextCloud, Nodepilot, Presearch, Subsquid, Taiga, Umbrel, and WordPress).

I followed the same code structure and changed requests as https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2743.

### Related Issues

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1841

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Review by maayarosama — COMMENTED** [review]
Missing Static Website and Caprover

**Comment by 0oM4R** [comment]
tested all added scripts and works fine, will approve once the comments got resolved

**Comment by A-Harby** [comment]
> Missing Static Website and Caprover

For the static website, I was just waiting for [issue](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2088) to be done so I could add it.

For the caprover, it was already created in the scripts from before so should I add them with the applications directory or just leave them, [leader](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/scripts/caprover_leader.ts) and [worker](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/scripts/caprover_worker.ts)

**Comment by maayarosama** [comment]
> > Missing Static Website and Caprover
> 
> For the static website, I was just waiting for [issue](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2088) to be done so I could add it.
> 
> For the caprover, it was already created in the scripts from before so should I add them with the applications directory or just leave them, [leader](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/scripts/caprover_leader.ts) and [worker](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/scripts/caprover_worker.ts)

Open an issue for the static website script.  And we can move the caprover scripts to the  applications directory

**Review by maayarosama — APPROVED** [review]

**Review by zaelgohary — APPROVED** [review]

**Pull request merged**
