### PR TITLE
Move filters to side instead of top

### PR DESCRIPTION
**Pull request by MohamedElmdary**
### Description
Moved filters to side instead of top

#### Farms page
image

#### Nodes Page
image

### Related Issues
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2515
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2129

### Documentation PR

For UI changes, Plaese provide the Documetation PR on [info_grid](https://github.com/threefoldtech/info_grid)

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Comment by ehab-hassan** [comment]
@MohamedElmdary can u make all filed and labels also button font size 0.875rem

**Review by zaelgohary — COMMENTED** [review]
Labels size look way too big compared to the side menu

image

**Review by zaelgohary — COMMENTED** [review]
Filters are not responsive. Maybe we should keep them horizontal in smaller screens?

image

**Comment by ehab-hassan** [comment]
image
apply button color change at a small size let's keep it a secondary color outlined

**Review by ehab-hassan — APPROVED** [review]

**Review by zaelgohary — APPROVED** [review]

**Comment by zaelgohary** [comment]
@MohamedElmdary  Amazing!

**Pull request merged**
