### PR TITLE
Improved the filtering functionality by consolidating filter options within the same form

### PR DESCRIPTION
**Pull request by Mahmoud-Emad**
### Description

1. Improved node filtering functionality by consolidating filter options within the same form, providing a more cohesive and user-friendly experience for managing filters.

2. Removed an unused farm options type and replaced it with the FilterOptions type.

3. Refactored the structure of the dedicated nodes page to enhance maintainability. Filters and associated functionality have been moved outside the nodes-table component, aligning with best practices. This ensures that the nodes-table component focuses solely on rendering the table without any embedded logic. (Work in progress)

4. Optimized code structure by relocating the 'loading' functionality from within the nodes-table component to its parent. Additionally, introduced a watcher on the active tab to emit an event when a tab is changed, providing a streamlined and event-driven approach for handling tab switches.

5. Added another input filter for 'Filter by region' in the filters, nodes components

### Changes

List of changes this PR includes

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1866
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1869

### Screenshots (if applicable)

- image
- image
- image

#### New changes 

- image

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Comment by AlaaElattar** [comment]
- The table should be empty if i added non existing region name.

[Screencast from 01-04-2024 05:40:41 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/cb26e905-c812-4645-86ae-d91c45837ed5)

**Review by AlaaElattar — APPROVED** [review]
- All working fine

**Comment by 0oM4R** [comment]
image
on nodes finder can we move the status field to the right like this picture ?

**Comment by 0oM4R** [comment]
[Screencast from 08 ينا, 2024 EET 12:56:40 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/b665240a-4278-4f1d-b75e-11977e78f058)
the added toggles and status changes applied without clicking on apply

**Review by 0oM4R — COMMENTED** [review]
if the user typed anything and before applying the changes decided to clear 
we will have the same inti request again,
we can check if we actually have  changes before send the request 

[Screencast from 08 ينا, 2024 EET 02:10:41 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/855c4300-c186-4dfb-9d26-683c9e7dbf58)

**Comment by 0oM4R** [comment]
> if the user typed anything and before applying the changes decided to clear we will have the same inti request again, we can check if we actually have changes before send the request
> 
>  Screencast.from.08.2024.EET.02.10.41.webm

the same on dedicated nodes

**Comment by AlaaElattar** [comment]
- Please fix the build

**Comment by 0oM4R** [comment]
update the screenshots please

**Comment by 0oM4R** [comment]
> after applying the added filters, the clear button is disabled, but if we applied the same scenario on the input fields the clear button is enabled normally. image

i can reproduce this

**Comment by 0oM4R** [comment]
https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1877#issuecomment-1880895102
https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1877#pullrequestreview-1808967595
https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1877#issuecomment-1880784337

please check those comments

**Review by mohamedamer453 — COMMENTED** [review]
- The region filter is not working and when the apply button is clicked it doesn't make a request and a request is only made when the clear button is clicked.

   [Screencast from 10-01-24 10:31:08.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/00c2dcbd-cf58-43ac-9574-68c3d26c4f8c)

- This message should be removed since now the user has to click the apply button for the filters to work.

   image

**Comment by Mahmoud-Emad** [comment]
@mohamedamer453 
Please make sure that you are on the latest code, I've tried now and all worked as well :) 

- [Screencast from 01-10-2024 10:52:23 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/ef303353-488a-4d1e-affa-04c881e72af3)

For the alert message, it's removed now, good suggestion :)

**Comment by mohamedamer453** [comment]
> @mohamedamer453
> 
> * Please make sure that you are on the latest code, I've tried now and all worked as well :)
>   

Indeed, it was an issue from my side, working fine now.

**Comment by Mahmoud-Emad** [comment]
PS

Based on @AhmedHanafy725 and @0oM4R call 

The whole filter needs to change, There should be 2 states, and enable/disable the `Apply` / `Clear` buttons to change the state itself

**Comment by AhmedHanafy725** [comment]
I can't apply after the swtich is back to the default state

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/db8585be-6db2-4418-b5ba-fa93d929c887

**Comment by 0oM4R** [comment]
We should disable the `Apply` if the next state is equal to the current state.
[Screencast from 10 ينا, 2024 EET 01:42:12 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/05a4af3b-954e-4944-9618-37f95fe5a675)

**Comment by 0oM4R** [comment]
> We should disable the `Apply` if the next state is equal to the current state.
> 
>  Screencast.from.10.2024.EET.01.42.12.webm

this is still happening with me

**Comment by AlaaElattar** [comment]
- The clear button not working 

[Screencast from 01-10-2024 04:41:58 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/9b8541a2-0c51-499c-85aa-ee37c38830fc)

**Comment by AlaaElattar** [comment]
> * The clear button not working
> 
>  Screencast.from.01-10-2024.04.41.58.PM.webm

It only cleares the filters.

**Comment by Mahmoud-Emad** [comment]
## Issue Update

### Work Completed:

- Implemented a feature to set filter values as query parameters by default, loading filters on page mount.
- Enhanced the filtering mechanism for nodes, farms, and dedicated machines, saving values as query parameters and loading them on page load.
- Resolved an issue affecting the playground build, ensuring a stable and error-free environment.
- Improved code readability by replacing hardcoded conditions with the `Reflect.set()` method.
- Worked on displaying the apply button when the current state is equal to the initial state, enhancing user interaction.
- Implemented functionality to disable the apply button when the values of the current state are equal to the next state.
- Removed an unused line added for debugging purposes, streamlining the codebase.
- Fixed an issue related to resetting state values, ensuring proper functionality.
- Added an informative message to be displayed to the user if the state has values selected.
- Implemented a fix to disable buttons during loading processes, preventing unintended user actions.
- Addressed a table page/size issue, ensuring proper loading of nodes upon page change.

### Work in Progress (WIP):

- Enable the apply button on change

**Comment by AhmedHanafy725** [comment]
the apply button should be enabled once any filter changes the current state of the filters.

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/fc5bed46-9a05-4b86-b643-288d418bdcf6

**Comment by 0oM4R** [comment]
> * if the filter values are different than the current state values, the `apply` button should be active.

- type in any field then click on apply
- go to another field and type any thing and delete it without clicking apply 
- the expected scenario is to disable the `Apply` btn but it was enabled

[Screencast from 11 ينا, 2024 EET 05:19:37 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/1d7b3b19-1d34-4040-8e26-8dd15b64bb28)

**Review by 0oM4R — APPROVED** [review]
The code is functional and works fine with me currently. we may face some ux issues, but will open a separate issues for them. 

Thank you @Mahmoud-Emad  great work

**Pull request merged**
