### PR TITLE
Show sidebar if the user is not logged in

### PR DESCRIPTION
**Pull request by zaelgohary**
### Description

- Now user can navigate all pages except for portal, solutions & contracts if not logged in
- Disabled calculate w user balance if not logged in

image

image

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1314

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Comment by AhmedHanafy725** [comment]
the calculator is broken when the user is not logged in

image

**Review by mohamedamer453 — COMMENTED** [review]
- When the screen in minimized, the icon for opening the sidebar appears but it's disabled.

   image

- Nodes and farms are not shown if the user isn't logged in. i think both should be shown since they contain data that the user might need without logging in.

- Deployment cost from the pricing calculator is completely different when the user is logged out.

   - logged out
   
      image
   
   - logged in 

      image

**Comment by zaelgohary** [comment]
@mohamedamer453 I fixed the sidebar btn. As for the calculations, I tried when logged in or not and got the same result as seen below. Can you tell me the scenario you made?

Logged in:
image


Logged out:
image

**Comment by AlaaElattar** [comment]
- The color of cards not changed 

[Screencast from 12-17-2023 11:19:41 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/5af6fa75-c722-4358-903b-fd869e640cf0)

**Comment by AlaaElattar** [comment]
- cards are not available 

image

**Comment by AlaaElattar** [comment]
- when i type smth in balance while I'm logged out, it doesn't reflect in cards. Is that intentional ??

**Comment by amiraabouhadid** [comment]
when i log in then log out i get this error in the calculator and the calculated costs are still shown even though i logged out 
image

**Comment by amiraabouhadid** [comment]
wouldn't it be better if we displayed a message to the user if he/she selects user farms or any other page that isnt available before login?

**Comment by AlaaElattar** [comment]
Should calculator work when user logs out or not ?

**Comment by zaelgohary** [comment]
> Should calculator work when user logs out or not ?

Yes.

**Comment by zaelgohary** [comment]
> when i log in then log out i get this error in the calculator and the calculated costs are still shown even though i logged out image

Calculator is supposed to be shown whether the user is logged in or not. I tried now and couldn't find the error shown in the console. Can you try again?

**Comment by zaelgohary** [comment]
> wouldn't it be better if we displayed a message to the user if he/she selects user farms or any other page that isnt available before login? A message like "Please login to view page"? Otherwise it feels counter intuitive to be redirected to pages but still get the same welcome screen.

done.

**Comment by AlaaElattar** [comment]
- Why the value change once i log out ??

[Screencast from 12-17-2023 05:04:23 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/845fffbf-cb17-470f-9e1d-92ad019cd947)

**Review by AlaaElattar — APPROVED** [review]
- Great Job

**Review by amiraabouhadid — APPROVED** [review]

**Pull request merged**
