### PR TITLE
Accept terms and conditions dialog enhancements

### PR DESCRIPTION
**Pull request by Mahmoud-Emad**
### Description

The idea is to parse the `MD` content of the `terms and conditions` and put it in a `v-dialog` instead of loading it in `iframe`

### Changes

- re-design the legal image
- re-design the code-block
- re-design the dialog
- scroll down to accept
- disable the accept button until the user reach the end of the dialog

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1413

### Screenshots/Video

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/2c0b0a73-9748-4c42-995d-acb7b3e5e1ae

### Checklist

- [ ] Tests included
- [x] Build pass
- [ ] Documentation
- [x] Code format and docstrings
- [x] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Comment by Mahmoud-Emad** [comment]
Converted to draft till we merge the `development 3.14` into the `development` branch

**Review by zaelgohary — CHANGES_REQUESTED** [review]
The new design looks terrific! Just one issue, whenever I click create account, the mnemonic field gets populated with my current password, not the new mnemonic. This doesn't happen on dev.

[terms&conditions.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/70c701be-8423-45b8-92f9-f143372bb926)

**Comment by AhmedHanafy725** [comment]
> The new design looks terrific! Just one issue, whenever I click create account, the mnemonic field gets populated with my current password, not the new mnemonic. This doesn't happen on dev.
> 
>  terms.conditions.webm

I believe Chrome is doing that by auto-filling the password field, please try this in an incognito window

**Comment by AhmedHanafy725** [comment]
it looks much better! but there is no way to go back if I decide not to create an account

**Comment by Mahmoud-Emad** [comment]
> it looks much better! but there is no way to go back if I decide not to create an account

Updated 

image

**Review by AhmedHanafy725 — APPROVED** [review]

**Review by zaelgohary — APPROVED** [review]
Good job, Emad!

**Pull request merged**
