### PR TITLE
Remove dedicated page, remove unused code from node finder

### PR DESCRIPTION
**Pull request by zaelgohary**
### Description

- Remove dedicated page
- Remove dedicated route
- Remove unused code from node finder
- Fix import in node finder

image

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2575

### Checklist

- [ ] Tests included
- [x] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [x] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Comment by 0oM4R** [comment]
also we may keep the old rout and make it refer to the node finder page to avoid 404 page later

**Comment by Mahmoud-Emad** [comment]
> also we may keep the old rout and make it refer to the node finder page to avoid 404 page later

I prefer this situation, @zaelgohary  please keep the route of the dedicated nodes page as it but redirect the request to the node finder

**Comment by zaelgohary** [comment]
@0oM4R applied comments. Also, opened an issue for the manual to be updated [here](https://github.com/threefoldtech/info_grid/issues/507)

**Review by samaradel — APPROVED** [review]
Nice!

**Pull request merged**
