### PR TITLE
Remove default VProgressCircular color

### PR DESCRIPTION
**Pull request by samaradel**
### Description

- Override button ```VProgressCircular``` color.
- Fix ```vm``` deleting spinner color.

### Changes

-Add color primary to components loader.

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2650

### Checklist

- [ ] Tests included
- [x] Build pass
- [ ] Documentation
- [x] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Comment by MohamedElmdary** [comment]
can't we just override `VBtn -> VProgressCircular`

```ts
const vuetify = createVuetify({
  defaults: {
    VAlert: {
      variant: "tonal",
    },
    VProgressCircular: {
      size: 50,
      width: 7,
      color: "primary",
    },
    VBtn: {
      VProgressCircular: {
        color: undefined,
      },
    },
  },
  // ...
  })
```

will result in returning them to inherit from button (it's parent)
image

**Comment by Mahmoud-Emad** [comment]
The color is still different here 

- [Virtual Machines](https://dashboard.dev.grid.tf/#/deploy/virtual-machines/)

image

**Comment by samaradel** [comment]
@Mahmoud-Emad fixed
image

**Review by MohamedElmdary — APPROVED** [review]

**Review by amiraabouhadid — COMMENTED** [review]
when i delete a vm contract i do not get a spinner on the delete button in the dialog, 
however, i get red spinners in the table 
image

**Comment by MohamedElmdary** [comment]
@amiraabouhadid that's because we don't have loading on button

image

**Review by amiraabouhadid — APPROVED** [review]

**Pull request merged**
