### PR TITLE
Dao proposal share button 

### PR DESCRIPTION
**Pull request by amiraabouhadid**
### Changes

- added a share button to the dao proposal card
- when pressed, a link is copied to the clipboard
- when link is entered in browser, it opens up dao page with shared proposal card highlighted 

### Related Issues

#3066

### Tested Scenarios

- press share button on any executable/active proposal 
- observe copied to clipboard success toast appear 
- enter linked copied in a new browser tab
- observe shared proposal card highlighted based on selected app theme

### Checklist

- [x] Tests included
- [x] Screenshots/Video attached (needed for UI changes)
https://www.loom.com/share/97f1e9fffe654007a04a916d62468371?sid=1877c39c-f354-451c-b96e-e2a13184b5c0

### CODE REVIEW

**Comment by xmonader** [comment]
Di really nice feature!!!

**Comment by amiraabouhadid** [comment]
@xmonader @ehab-hassan  should i open up a dialog with shared proposal or leave it highlighted as it is in screencast?

**Comment by xmonader** [comment]
> @xmonader @ehab-hassan should i open up a dialog with shared proposal or leave it highlighted as it is in screencast?

Helwa kda imo
image

**Comment by ehab-hassan** [comment]
> @xmonader @ehab-hassan should i open up a dialog with shared proposal or leave it highlighted as it is in screencast?

looks nice to me

**Review by maayarosama — COMMENTED** [review]
Can we navigate to executable tab directly after pasting the link in a new tab?

**Review by maayarosama — APPROVED** [review]

**Review by samaradel — APPROVED** [review]

**Pull request merged**
