### PR TITLE
Add TFT-USD exchange rate 

### PR DESCRIPTION
**Pull request by AlaaElattar**
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1072
- The user can check exchange rate whether it's connected to wallet or not.
- Position may seem odd, but it will be handled after merging with `Get Button`.

Screenshot from 2023-09-12 17-21-47

Screenshot from 2023-09-12 17-22-00

image

### CODE REVIEW

**Review by Mahmoud-Emad — CHANGES_REQUESTED** [review]
I think if it is near the title `Threefold` it'll be good

**Comment by AlaaElattar** [comment]
- The position with `Get TFT` button.
Screenshot from 2023-09-21 18-05-48

**Comment by Mahmoud-Emad** [comment]
Great job :)

I think that we need to give some attention to the responsive 
image

**Comment by AlaaElattar** [comment]
https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/0246412f-5c7d-4d05-b74b-f76bfef18fa4

**Comment by AlaaElattar** [comment]
image

**Review by zaelgohary — APPROVED** [review]

**Pull request merged**
