### PR TITLE
Enhance inputs in light theme

### PR DESCRIPTION
**Pull request by samaradel**
### Description

Enhance UI components in light theme 
### Changes

image
image
image
image
image
image
image
image
image

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2674
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2734
### Checklist

- [ ] Tests included
- [x] Build pass
- [ ] Documentation
- [x] Code format and docstrings
- [x] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Comment by Mahmoud-Emad** [comment]
i don't know if it feasible or not but when hover on a country in the statistic page I see the tooltip dark in light theme 

image

**Comment by Mahmoud-Emad** [comment]
most of the inputs are still not dealing with the light theme, look at the simulator page, Do you think it needs to be `outlined` in the light mode?

image

**Comment by Mahmoud-Emad** [comment]
The colors here also are not clear at all 

image

**Comment by maayarosama** [comment]
- In the home page:
1. Map  doesn't look clear at all 
2. I can't really see the ``` learn about the grid ```  button, so I suggest changing its color to mint green  like the ``` get tft``` button 
3. The icon below the map aren't clear, can we make the color more intense so they became clearer?

![Screenshot from 2024-05-21 11-13-49](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/cc885198-5563-48bd-8ff0-008ff12e2aa2)


- In pricing calculator page:

1. The gradient gold package doesn't look good against the bright white background, I suggest removing the bright intense white background across the dashboard and making it less intense  white color or  a light gray 

![Screenshot from 2024-05-21 11-13-49](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/cc885198-5563-48bd-8ff0-008ff12e2aa2)

                                                                                                                                                                                                                                                                                                          
- In node finder page:

1. the progress bar, The unfilled part is not really clear against the white background, I suggest increasing the opacity a little bit

![2024-05-21_11-34](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/76ac32d0-aae6-432f-bb0d-f062bb7aeb44)



- In the applications page:

1. the static website's icon has a black background

![Screenshot from 2024-05-21 11-38-24](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/24a2b510-bed7-4fa1-ba80-f0f6eaff5bf7)


- In simulator page:

1. Values in disabled field aren't clear
![Screenshot from 2024-05-21 11-46-55](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/f024e884-8dd8-4531-b7dc-9f28bf8659e4)

**Comment by ehab-hassan** [comment]
> i don't know if it feasible or not but when hover on a country in the statistic page I see the tooltip dark in light theme
> 
> image

I tried to enhance the UI before but when I checked with @MohamedElmdary it was hard to adjust here, also I think we'll use a new map soon so let's leave it as is for now.

**Comment by ehab-hassan** [comment]
@maayarosama For the gradient gold package if we change the white BG for the dashboard will not be consistent with other pages but we can add a border that'll make it clearer, what do you think?
image

**Comment by maayarosama** [comment]
> @maayarosama For the gradient gold package if we change the white BG for the dashboard will not be consistent with other pages but we can add a border that'll make it clearer, what do you think? image

I suggest changing the white background across all the dashboard, As the white is too bright and it's harsh on the eyes, what do you think @ehab-hassan ?

**Review by Mahmoud-Emad — APPROVED** [review]
Thanks ya Samar, Go ahead

**Pull request merged**
