### PR TITLE
Fix getting user nodes in portal 

### PR DESCRIPTION
**Pull request by 0oM4R**
### Changes

if the array of the user farms is empty, we return an empty array

image

### Related Issues

- #1504 
> i suggested some enhancements to the related components : - #1508
### Checklist

- [ ] Tests included
- [x] Build pass
- [ ] Documentation
- [x] Code format and docstrings
- [x] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Review by amiraabouhadid — CHANGES_REQUESTED** [review]
set total num of nodes to 0 before returning

**Review by xmonader — APPROVED** [review]

**Review by Mahmoud-Emad — APPROVED** [review]
LGTM, Please fix the Nan in the nodes pagination

**Comment by 0oM4R** [comment]
image

fixed thank you!

**Review by amiraabouhadid — APPROVED** [review]
verified, thanks
image

**Pull request merged**
