### PR TITLE
Fix decimal err in dedicated filters

### PR DESCRIPTION
**Pull request by zaelgohary**
### Description

- Used Math.floor with values as Grid Proxy doesn't accept float values
- Refactored NodesQuery
- Added filter by total resources in nodes page
- Fixed formatResources
- Fixed filter by decimal in nodes & dedicated nodes

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1725
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1783

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Comment by 0oM4R** [comment]
Screenshot from 2023-12-24 11-13-58

Ram field does not accept decimal number
and i don't think it's a good idea to use floor, I suggest to use ceil

**Comment by amiraabouhadid** [comment]
I tried it with exact RAM value but it failed 
image
Screenshot from 2023-12-21 15-02-56

**Comment by zaelgohary** [comment]
> I tried it with exact RAM value but it failed image image

The value in the table was rounded. Fixed by showing the value without any rounding.

**Review by amiraabouhadid — APPROVED** [review]
thanks for adding it nodes page too
image

**Review by 0oM4R — APPROVED** [review]

**Pull request merged**
