### PR TITLE
Add mycelium IP column in workers table

### PR DESCRIPTION
**Pull request by samaradel**
### Description

- Add the MyCelium IP column in the worker's table.
- Include myCelium in the worker deployment object.
- Add `Created At` and `Health` columns.

### Changes

image
### Tested Scenarios

- Go to `Caprover` solution
- Deploy instance with worker and mycelium enabled
- List the deployments 
- View the worker's table, the mycelium column should be there

### Scenarios update

- Create more than two workers and check that all have the mycelium IP column.
- Create with planetary and no mycelium and check nothing in the mycelium column.
- Delete a worker, add it again, and ensure mycelium ip changes.

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3446

### Checklist

- [x] Tests included
- [x] Build pass
- [ ] Documentation
- [x] Code format and docstrings
- [x] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Comment by samaradel** [comment]
cpd from https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3590

**Comment by maayarosama** [comment]
Shouldn't we apply this to k8s workers too?

**Review by amiraabouhadid — APPROVED** [review]

**Comment by AhmedHanafy725** [comment]
> Shouldn't we apply this to k8s workers too?

please have a different issue for it

**Review by ramezsaeed — APPROVED** [review]

**Review by 0oM4R — COMMENTED** [review]
the workers table contain contract id 
image


while the deployment doesn't have it should we remove it ?
image

**Comment by samaradel** [comment]
@0oM4R I'm not sure, I sent the current solution to the SDK group and @AhmedHanafy725 agreed. maybe he should confirm.

**Comment by AhmedHanafy725** [comment]
> @0oM4R I'm not sure, I sent the current solution to the SDK group and @AhmedHanafy725 agreed. maybe he should confirm.

no problem, we can remove it from the table

**Review by maayarosama — APPROVED** [review]

**Pull request merged**
