### PR TITLE
restore old profile popup

### PR DESCRIPTION
**Pull request by amiraabouhadid**
### Changes
- changed direct deposit dialog back to the old profile popup

### Related Issues

#1934

image

### CODE REVIEW

**Comment by AlaaElattar** [comment]
- when i click outside the dialog, it won't close.
- also we should add close btn.

**Comment by amiraabouhadid** [comment]
> * when i click outside the dialog, it won't close.
> * also we should add close btn.

restored to old profile pop up as instructed

**Comment by AlaaElattar** [comment]
- please resolve conflicts

**Review by 0oM4R — APPROVED** [review]
image

**Review by AlaaElattar — APPROVED** [review]

**Pull request merged**
