### PR TITLE
Add Back Button in second navbar

### PR DESCRIPTION
**Pull request by AlaaElattar**
### Description

- If used logged out, the navbar would still be available
### Changes

Add Condition no navbar, won't appear unless user logged in.
### Related Issues

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1586

[Screencast from 12-10-2023 11:14:52 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/0621ad81-91f7-4290-b889-b8e04a186f34)

### Checklist

- [ ] Tests included
- [x] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [x] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Comment by MohamedElmdary** [comment]
Please reverse back btn position with the path in second navbar

**Comment by AlaaElattar** [comment]
> Please reverse back btn position with the path in second navbar

I don't understand your comment. Would you please explain more ?

**Comment by AlaaElattar** [comment]
- Positions swapped.
image

**Comment by ehab-hassan** [comment]
Why do we have 2 things with the same function? also putting Breadcrumb at the right is wired to the user, I think one is enough and to be at the left, also Breadcrumbs is better than the back button

**Comment by AlaaElattar** [comment]
> Why do we have 2 things with the same function? also putting Breadcrumb at the right is wired to the user, I think one is enough and to be at the left, also Breadcrumbs is better than the back button

Qa returned it in progess and asked for back button to be added

**Comment by xmonader** [comment]
For me this 
image

looks very clear as a breadcrumb (it's expected each item in that path to be clickable to get me back to where I was -except for the current page of course-

Similar designs 

image

image

image

and some use `/` instead of `>`

image

All in all, it seems to be implicit how to use breadcrumbs UX wise, even no need to underline the trail

**Comment by xmonader** [comment]
I'll close this one and the other two issues (@AlaaElattar thank you so much!)

**Comment by AlaaElattar** [comment]
- Button removed and breadcrumb at left

**Comment by A-Harby** [comment]
I didn't say to move it to the right side what I meant is that it is kind useless to have a breadcrumb for only one page navigation and back button on the right side would be enough.

**Review by 0oM4R — APPROVED** [review]

**Review by maayarosama — APPROVED** [review]

**Comment by xmonader** [comment]
> I didn't say to move it to the right side what I meant is that it is kind useless to have a breadcrumb for only one page navigation and back button on the right side would be enough.

I understand now what you meant, similar to this 
image

I added this comment for documentation purposes

**Pull request merged**
