### PR TITLE
Adjust node details columns height

### PR DESCRIPTION
**Pull request by samaradel**
### Description

- Adjust node details column height
- Decrease node details card width
- Merge location and country cards in one card 
- Decrease node resources chart dimension
### Changes

image
image
image

### Related Issues

- [2160](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2160)

### Checklist

- [ ] Tests included
- [x] Build pass
- [x] Documentation
- [x] Code format and docstrings
- [x] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Review by amiraabouhadid — CHANGES_REQUESTED** [review]
Please adjust breakpoints so that the stellar address is similar to other rows in the cards and not placed on a new line while other details are on the same line for the same view width
image

**Comment by samaradel** [comment]
image

fixed on small screens

**Comment by zaelgohary** [comment]
> image
> 
> fixed on small screens

Can we make the width take 1 card only on smaller screens?

**Comment by samaradel** [comment]
@zaelgohary Done

**Review by zaelgohary — COMMENTED** [review]
Issue is still not fixed.

image

**Review by zaelgohary — APPROVED** [review]
Good job, Samar.

**Review by AlaaElattar — APPROVED** [review]

**Pull request merged**
