### PR TITLE
Update application tests with Mycelium

### PR DESCRIPTION
**Pull request by A-Harby**
### Description

Update application tests with Mycelium, just enabled and add assertion.

### Changes

Application tests

### Related Issues

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2958
https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3512

### CODE REVIEW

**Comment by A-Harby** [comment]
https://github.com/threefoldtech/tfgrid-sdk-ts/runs/31240774792#r0s23

**Review by khaledyoussef24 — APPROVED** [review]

**Comment by 0oM4R** [comment]
> https://github.com/threefoldtech/tfgrid-sdk-ts/runs/31240774792#r0s23

There are some tests failed, are they tracked in another issue if not related to this pr ?

**Comment by samaradel** [comment]
till now and many cases keep failing.
image

**Comment by A-Harby** [comment]
> till now and many cases keep failing. image

There're multiple issues for the application flist because they are not stable at all, but tests are working fine.
https://github.com/threefoldtech/tf-images/issues/294, https://github.com/threefoldtech/tf-images/issues/226, https://github.com/threefoldtech/tf-images/issues/225, and else.

and for zmount new issue is created https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3523.

**Review by 0oM4R — APPROVED** [review]

**Comment by AhmedHanafy725** [comment]
The failing tests are not related to the main purpose of this PR

**Pull request merged**
