### PR TITLE
Fix profile input resetting

### PR DESCRIPTION
**Pull request by zaelgohary**
### Changes

- Change the condition to v-show instead of v-if so the forms wouldn't be destroyed if tab is changed

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/919

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Review by Mahmoud-Emad — COMMENTED** [review]
I think the change you did doesn't fix the issue

**Comment by zaelgohary** [comment]
@Mahmoud-Emad I think it does. :D
[screen-capture.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/e83054ca-76eb-4225-a302-878dc2036dff)

**Comment by Omarabdul3ziz** [comment]
Hi, what i noticed is `close` button does something different than clicking outside the profile component.
if you click close button it do clear the fields but clicking outside the component will not

**Comment by Mahmoud-Emad** [comment]
@Omarabdul3ziz 
Exactly :)

**Comment by Omarabdul3ziz** [comment]
yes this works.
a small final comment after you do logout, fields are still there only if you close the component it gets cleared. could we make logout clear the fields also or what do you think?

**Comment by zaelgohary** [comment]
@Omarabdul3ziz I couldn't use clearfields method as the refs get destroyed so I reset the fields one by one.

**Review by Omarabdul3ziz — APPROVED** [review]

**Pull request merged**
