### PR TITLE
Update farm name validation

### PR DESCRIPTION
**Pull request by amiraabouhadid**
### Changes

Added validation for farm name to check if farm name exists in all farms on tfchain

### Related Issues

#2764

### Documentation PR

For UI changes, Please provide the Documetation PR on [info_grid](https://github.com/threefoldtech/info_grid)

### CODE REVIEW

**Review by maayarosama — CHANGES_REQUESTED** [review]
You shouldn't list all Farms, you should filter by farm name from the grid proxy and it the Farm exists then you should display it as a field validation error and block the creating of the farm

**Comment by MohamedElmdary** [comment]
shouldn't we remove the unused code?
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/playground/src/dashboard/components/create_farm.vue#L82-L85
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/playground/src/dashboard/farms_view.vue#L8-L9
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/playground/src/dashboard/farms_view.vue#L28-L33
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/playground/src/dashboard/components/user_farms.vue#L332-L344

**Comment by MohamedElmdary** [comment]
@amiraabouhadid if component no longer getting userFarms as ref so should we remove it's code?

https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/playground/src/dashboard/farms_view.vue#L8-L9

https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/playground/src/dashboard/farms_view.vue#L28-L33

**Review by maayarosama — APPROVED** [review]

**Review by Mahmoud-Emad — APPROVED** [review]
Good job ya Amira :)

**Pull request merged**
