### PR TITLE
update stats link

### PR DESCRIPTION
**Pull request by mohamedamer453**
### Description

Updated stats link in the landing page.

### Changes

Updated `Explore Threefold gird capacity` button to redirect to https://newstats.dev.grid.tf/

### Related Issues

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1589

### Checklist

- [ ] Tests included
- [x] Build pass
- [ ] Documentation
- [x] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Review by AlaaElattar — COMMENTED** [review]
Why `https://newstats.dev.grid.tf/` is the only one that's reachable ??

**Comment by mohamedamer453** [comment]
> Why `https://newstats.dev.grid.tf/` is the only one that's reachable ??

I believe it's the only one reachable since it's not deployed on other networks yet.

**Review by AlaaElattar — APPROVED** [review]

**Comment by AhmedHanafy725** [comment]
It should redirect to the statistics page on the dashboard

**Comment by mohamedamer453** [comment]
> It should redirect to the statistics page on the dashboard

Converted to draft since the issue is currently blocked as mentioned in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1589#issuecomment-1848923052, because the user currently cannot access the stats page without logging in.

**Pull request closed without merging**
