### PR TITLE
add scripts and tests

### PR DESCRIPTION
**Pull request by khaledyoussef24**
### Description

add scripts and tests
#1841 
### Changes

List of changes this PR includes
tests and scripts for all of the solutions

### Related Issues

List of related issues

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Review by AlaaElattar — COMMENTED** [review]
- you should add `mycelium` flag, it's mandatory just as planetary. 
- all scripts won't run without it.
image

**Comment by khaledyoussef24** [comment]
wip : 
adding the flag to all of the scripts and tests

**Comment by xmonader** [comment]
@khaledyoussef24 please make sure next time to use a proper branch name `development_new_scripts` means nothing

**Comment by khaledyoussef24** [comment]
okay, will make sure next time that it would be more descriptive.
can i make a sub-folder inside the scripts for the applications?

**Pull request closed without merging**
