### PR TITLE
Add cancel all contracts button

### PR DESCRIPTION
**Pull request by 0oM4R**
### Description

Add unlock all contracts buttons, and add unlock icon

### Changes

- image

- image

### Related Issues

- #3056 

### Documentation PR

For UI changes, Please provide the Documetation PR on [info_grid](https://github.com/threefoldtech/info_grid)

### Checklist

- [ ] Tests included
- [x] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [x] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Review by amiraabouhadid — APPROVED** [review]

**Review by zaelgohary — CHANGES_REQUESTED** [review]
image

Can we put this in a warning too?

**Review by Mahmoud-Emad — APPROVED** [review]

**Comment by zaelgohary** [comment]
Also, do we have to wait for 30 secs to display empty tables? Can't we just display no contracts on the spot?

**Comment by 0oM4R** [comment]
> Also, do we have to wait for 30 secs to display empty tables? Can't we just display no contracts on the spot?

This is the current behavior with delete contracts the tables got updated after 30 min I think it should be the same

**Comment by ehab-hassan** [comment]
> image
> 
> Can we put this in a warning too?

It should be both at one alert but "You are about ..." at the first line then "Deleting cont.."

**Comment by 0oM4R** [comment]
Screenshot from 2024-08-05 13-18-08

**Review by zaelgohary — APPROVED** [review]

**Review by maayarosama — APPROVED** [review]

**Pull request merged**
