### PR TITLE
Add rentableOrRentedBy query in dedicated filter

### PR DESCRIPTION
**Pull request by samaradel**
### Description

- Add ```rentableOrRentedBy``` query in the dedicated filter.
- merging development branch.

### Changes

[Screencast from 04-11-24 16:30:07.webm](https://github.com/user-attachments/assets/c5001aec-fd6d-4afc-87bd-0191c51fab53)

### Tested Scenarios

- Go to any solution page
- Toggle on the Dedicated node switch
- Load Nodes and you'll find the nodes you already rented and the nodes that are available for you to rent

### Scenarios Update

- Rent a node and make sure it's not listed in the free dedicated nodes filter.
- Unreserve the node and ensure it is back in the free dedicated node filter.
- Try to deploy on a node not rented by you (should fail with proper error message)

### Documentation PR
- https://github.com/threefoldtech/info_grid/issues/705

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2775

### Checklist

- [x] Tests included
- [x] Build pass
- [x] Documentation
- [x] Code format and docstrings
- [x] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Comment by amiraabouhadid** [comment]
i think a switch like this is missing for rentable based on the issue description. 
image

**Review by 0oM4R — CHANGES_REQUESTED** [review]
missing tested scenarios, please update the pr description to include them

**Comment by maayarosama** [comment]
shouldn't we add a new switch for rentable or rented by me nodes, and if case that we don't shouldn't we adjust the tooltip of the dedicated switch

**Comment by samaradel** [comment]
@maayarosama, the case is already handled with the `rentable_or_rented_by` filter. 
Maybe we need to add this part to the docs info as it has extra behavior compared with the `dedicated nodes` we have on the node finder page. @AhmedHanafy725, what do you think?

**Review by ramezsaeed — CHANGES_REQUESTED** [review]
Test scenarios:
- rent a node and make sure its not listed in the free dedicated nodes filter.
- unreserve the node and make sure its back again in the free dedicated node filter.
- try to deploy on a node not rented by you (should fail with proper error message)

**Comment by AhmedHanafy725** [comment]
> shouldn't we add a new switch for rentable or rented by me nodes, and if case that we don't shouldn't we adjust the tooltip of the dedicated switch

I agree with updating the tooltip

**Comment by AhmedHanafy725** [comment]
> @maayarosama, the case is already handled with the `rentable_or_rented_by` filter. Maybe we need to add this part to the docs info as it has extra behavior compared with the `dedicated nodes` we have on the node finder page. @AhmedHanafy725, what do you think?

good to have docs for it, but I don't see a difference between the deploy node filter and the node finder page.

**Comment by samaradel** [comment]
@AhmedHanafy725 As the issue was asked for, we created the filter so the user can reserve/unreserve from the nodes which is available for him. 
image

**Comment by ramezsaeed** [comment]
please confirm these scenarios had been tested; and add them to the PR body.
https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3587#pullrequestreview-2445690707

**Comment by samaradel** [comment]
> please confirm these scenarios had been tested; and add them to the PR body. [#3587 (review)](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3587#pullrequestreview-2445690707)

already tested and added 
image

**Review by ramezsaeed — APPROVED** [review]

**Review by maayarosama — CHANGES_REQUESTED** [review]
Should we adjust the tooltip to explain what exactly the dedicated switch retrieves?

**Comment by samaradel** [comment]
> Should we adjust the tooltip to explain what exactly the dedicated switch retrieves?

issue created https://github.com/threefoldtech/info_grid/issues/705

**Review by maayarosama — APPROVED** [review]

**Review by 0oM4R — COMMENTED** [review]
there are about 3 rentable nodes in node finder but i can't get any of them listed in the deploy section 

[Screencast from 2024-12-15 12-41-29.webm](https://github.com/user-attachments/assets/e4f7f007-6f70-406d-8fa8-54cb94afa32b)

after reserving node 151 it got listed without any other rentable nodes

**Comment by samaradel** [comment]
@0oM4R fixed

**Pull request closed without merging**
