### PR TITLE
Reduce vm Listing time in main net

### PR DESCRIPTION
**Pull request by AlaaElattar**
### Description
- Listing vms takes much time if any deployments failed to load.
- There's max 60 seconds trial before saying we failed to get the deployments

### Changes

- I added race condition and timeout for 5 seconds instead of 60.

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1213

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/b3c3c867-5698-4252-a175-f0fd85b9e491

### CODE REVIEW

**Comment by AlaaElattar** [comment]
- I will also apply the same for k8s.

**Comment by zaelgohary** [comment]
I tried to load deployments and it showed me this err: 

image

I think this issue is already fixed in another PR.

**Comment by AlaaElattar** [comment]
> I tried to load deployments and it showed me this err:
> 
> image
> 
> I think this issue is already fixed in another [PR](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1268)

yes that's because chunk 3, already fixed in the other pr.

**Comment by AhmedHanafy725** [comment]
the fix is already done on the development branch

**Pull request closed without merging**
