### PR TITLE
Replace polkadot extension signer with tfchain wallet connector signer in portal

### PR DESCRIPTION
**Pull request by MohamedElmdary**
## Issues
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/470

image

### CODE REVIEW

**Comment by AhmedHanafy725** [comment]
first testing round:
- before the login page looks so bad
image

- after the first login, it didn't move to the account page
image

- after logout, the balance is still there, the navbar is corrupted, and still can see the info of the previously logged-in user
image

- set extra fee is not working, still depending on the extension
image

**Comment by 0oM4R** [comment]
#### same issues Hanafy mentioned above;
[Screencast from 19 يول, 2023 EEST 11:50:44 ص.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/68fbd26e-b632-404e-b475-cdc5f3cead8e)

### generate account btn not working

[Screencast from 19 يول, 2023 EEST 11:59:45 ص.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/8879c347-8611-4347-8a12-51c4ee3c167d)


#### suggestions: 
1- remove shh field there is no need for it here 
2- add btn to show the password and the Mnem before login

**Comment by 0oM4R** [comment]
tried to run the dashboard on qa net but after login it keep loading forever and show the balance of the account on dev
new connector on qa:
image
dashboard on qa: 
image

**Comment by 0oM4R** [comment]
#### testing portal 
- [ ] twin :x:  
   - have some issues mentioned previously 
- [ ] Bridge
- [x] transfer :heavy_check_mark: 
- [ ] Farm :x: 
   - "set extra fee is not working, still depending on the extension"
- [ ] Dedicated Nodes 
- [ ] DAO

**Review by 0oM4R — APPROVED** [review]

**Review by AhmedHanafy725 — APPROVED** [review]

**Pull request merged**
