### PR TITLE
Development 313 revamp sidebar

### PR DESCRIPTION
**Pull request by amiraabouhadid**
### Description

#1445 

### Changes

Changed Portal to Dashboard.
Moved Contracts to Dashboard
Moved 0-hub, 0-bootstrap, grid services & manual to Services
Removed Explorer and placed Stats, Nodes and Farms separately.

image

### CODE REVIEW

**Review by mohamedamer453 — COMMENTED** [review]
The current naming/folder structure is a bit confusing. there's a dashboard directory in `/src/dashboard` which contains a `components` folder and there's another dashboard directory in `/src/components/dashboard` that contains a couple of components. i think it would be less confusing if the components in  `/src/components/dashboard` were moved to `/src/dashboard/components` and the dashboard directory that's inside `src/components` was removed.

**Review by mohamedamer453 — COMMENTED** [review]
Another minor improvement would be bringing the solutions and calculators above the Statistics so the order would be:

- Dashboard
- Calculators
- Solutions
- Statistics
- Nodes
- Farms
- Services

**Review by zaelgohary — DISMISSED** [review]
The route here needs to be fixed.

https://github.com/threefoldtech/tfgrid-sdk-ts/blob/1fb81e471f154163b84eabc78c29324c8318d79e/packages/playground/src/dashboard/twin_view.vue#L125

**Comment by zaelgohary** [comment]
This line also needs to be edited.

https://github.com/threefoldtech/tfgrid-sdk-ts/blob/b57b6bc4f1b3d78f9da75af41f0ccfe3ea88d226/packages/playground/src/components/funds_card.vue#L18-L19

**Review by mohamedamer453 — APPROVED** [review]

**Review by Mahmoud-Emad — APPROVED** [review]
Good job ya Amira :)

**Pull request merged**
