### PR TITLE
Make the status of ```getNodeAvailability``` dynamic

### PR DESCRIPTION
**Pull request by samaradel**
### Description

Make the status of ```getNodeAvailability``` dynamic, it was ```down``` even it's ```standby```

### Changes

image_2024-06-25_12-58-49
### Related Issues

 - https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2900

### Checklist

- [ ] Tests included
- [x] Build pass
- [ ] Documentation
- [x] Code format and docstrings
- [x] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Review by 0oM4R — COMMENTED** [review]
image

is that normal ? node is up, but it says it was up for 0 sec ?

**Comment by samaradel** [comment]
I think it's just ```up``` from a second, @AhmedHanafy725 can you confirm?

**Comment by AhmedHanafy725** [comment]
> I think it's just `up` from a second, @AhmedHanafy725 can you confirm?

It wasn't up at all in the past seconds and just went up, is that the case?

**Comment by samaradel** [comment]
> > I think it's just `up` from a second, @AhmedHanafy725 can you confirm?
> 
> It wasn't up at all in the past seconds and just went up, is that the case?

it's what I got too, @0oM4R can you check the same node again please?

**Comment by 0oM4R** [comment]
> > > I think it's just `up` from a second, @AhmedHanafy725 can you confirm?
> > 
> > 
> > It wasn't up at all in the past seconds and just went up, is that the case?
> 
> it's what I got too, @0oM4R can you check the same node again please?

@samaradel  after about 1 hour 
image

**Comment by 0oM4R** [comment]
and for many other up nodes
image

**Pull request closed without merging**
