### PR TITLE
Add back button to solutions page

### PR DESCRIPTION
**Pull request by AlaaElattar**
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1315
- Added button with back arrow to return to solutions page from all solutions

Screenshot from 2023-11-02 14-59-03

### CODE REVIEW

**Review by amiraabouhadid — CHANGES_REQUESTED** [review]
maybe we need a wrapper around the solutions so that you add the back button only to the wrapper/container instead of adding it to each individual solution view

**Comment by AlaaElattar** [comment]
> maybe we need a wrapper around the solutions so that you add the back button only to the wrapper/container instead of adding it to each individual solution view

I handled it from component and removed calling from solutions.

**Comment by AlaaElattar** [comment]
- Arrow added here. 
- Add boolean var `isWeblets` in `weblet-layout` component to show arrow only if its from weblets page. 
image

**Comment by AlaaElattar** [comment]
- Updated using breadcrumbs `second navbar`.
- Solutions is clickable if user wants to go back to solutions page.
image

**Comment by ehab-hassan** [comment]
@AlaaElattar I think u need to make Solutions light green (secondary or info color) and no need for a gray background

**Comment by AlaaElattar** [comment]
> @AlaaElattar I think u need to make Solutions light green (secondary or info color) and no need for a gray background
- What do u think like that ?
image

**Comment by ehab-hassan** [comment]
@AlaaElattar perfect!!

**Review by 0oM4R — CHANGES_REQUESTED** [review]
should we add background color ?
image
while scrolling we need to make the bar more clear

**Comment by ehab-hassan** [comment]
> should we add background color ? image while scrolling we need to make the bar more clear

Sorry my bad I don't know if it is fixed at the top @AlaaElattar I think you need to put the background back

**Comment by AlaaElattar** [comment]
- Colors updated i both dark and light modes.

Screenshot from 2023-11-08 17-10-37

Screenshot from 2023-11-08 17-10-48

**Review by mohamedamer453 — COMMENTED** [review]
It would be great if we could navigate to the top of the page when selecting one of the solutions that are available at the bottom of the solutions page.

[Screencast from 09-11-23 15:34:02.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/374908f3-776d-441c-aea5-32b46d24a48c)

**Comment by AlaaElattar** [comment]
> It would be great if we could navigate to the top of the page when selecting one of the solutions that are available at the bottom of the solutions page.
> 
>  Screencast.from.09-11-23.15.34.02.webm

didn't get your point, explain more please

**Comment by mohamedamer453** [comment]
> > It would be great if we could navigate to the top of the page when selecting one of the solutions that are available at the bottom of the solutions page.
> > Screencast.from.09-11-23.15.34.02.webm
> 
> didn't get your point, explain more please

Selecting a solution like algorand or any other solution that's at the bottom of the solutions list will redirect the user to the solution page but the user will be redirected to the same position in the page which is scrolled down a bit and not at the top of the page.

**Comment by AlaaElattar** [comment]
> > > It would be great if we could navigate to the top of the page when selecting one of the solutions that are available at the bottom of the solutions page.
> > > Screencast.from.09-11-23.15.34.02.webm
> > 
> > 
> > didn't get your point, explain more please
> 
> Selecting a solution like algorand or any other solution that's at the bottom of the solutions list will redirect the user to the solution page but the user will be redirected to the same position in the page which is scrolled down a bit and not at the top of the page.

Issue Fixed

**Comment by mohamedamer453** [comment]
> Issue Fixed

[Screencast from 12-11-23 13:01:57.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/ca5c0ffb-3320-47e8-a703-c628947eaad2)

issue is still present, when i select any solution that's at the bottom of the solutions list, i get redirected to the same position in the solution not to the top of the page.

**Comment by AlaaElattar** [comment]
> > Issue Fixed
> 
>  Screencast.from.12-11-23.13.01.57.webm 
> issue is still present, when i select any solution that's at the bottom of the solutions list, i get redirected to the same position in the solution not to the top of the page.

I thought u meant the solutions page not each solution itself.

**Comment by mohamedamer453** [comment]
> I thought u meant the solutions page not each solution itself.

Sorry for the miscommunication, but i meant the solution itself since there're important parts that are skipped in the solution configuration if the user isn't redirected to the top of the page.

**Comment by AlaaElattar** [comment]
> > I thought u meant the solutions page not each solution itself.
> 
> Sorry for the miscommunication, but i meant the solution itself since there're important parts that are skipped in the solution configuration if the user isn't redirected to the top of the page.

I handled it, any page the user will be directed to will be at the top always.

**Review by mohamedamer453 — APPROVED** [review]

**Review by amiraabouhadid — APPROVED** [review]

**Review by 0oM4R — APPROVED** [review]

**Pull request merged**
