### PR TITLE
playground: custom Domain Name

### PR DESCRIPTION
**Pull request by 0oM4R**
### Description

- while loading farms the select gateway will be hidden
  image
- before deploy 

 [Screencast from 18 يول, 2023 EEST 06:39:03 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/f66ac791-444d-4ef0-8e0b-04c5eb10302f)

-__after deployment only__ deployment data dialog 
   image

Support custom domain name

### Changes
- change `GatewayFQDNModel` to allow longer names
- add an alert on deployments that use ipv4 with the custom domain in the deployment data dialog
- create a new component  for the domain Name
- create a new manager to link between farm and gateway nodes
- include the manager in select farm components.
- update select gateway node component.
- change `GatewayNode` interface
- allow delete solution that should have gateways if there is no contract with its name
- support DomainName component in some weblets
### Related Issues

- #670 

### Checklist

- [ ] Tests included
- [x] Build pass
- [ ] Documentation
- [x] Code format and docstrings
- [x] Screenshots/Video attached (needed for UI changes)

### CODE REVIEW

**Comment by MohamedElmdary** [comment]
Changing the farm after selecting a gateway causing the gateway input to reload (which is right) but the deploy button isn't disabled @0oM4R

**Comment by 0oM4R** [comment]
> Changing the farm after selecting a gateway causing the gateway input to reload (which is right) but the deploy button isn't disabled @0oM4R

should be fixed please try again @MohamedElmdary

**Comment by AhmedHanafy725** [comment]
when trying to deploy funkwhale instance with a custom domain and without public ip
image

**Comment by 0oM4R** [comment]
> when trying to deploy funkwhale instance with a custom domain and without public ip also the same with public ip image

should be fixed

**Comment by 0oM4R** [comment]
tested weblets: 
| weblet      | gateway | custom without ipv4 | custom with ipv4
| ----------- | ----------- | ----------- | ----------- |
| Freeflow      |         |    |         |
| Freeflow      |         |    |         |
| Freeflow      |         |    |         |
| Freeflow      |         |    |         |
| Freeflow      |         |    |         |

**Review by AhmedHanafy725 — APPROVED** [review]

**Pull request merged**
